from game_constructor.tateti_constructor import TatetiConstructor
from game_logic.tateti_implementation.console_implementation import ConsoleImplementation

console_implementation = ConsoleImplementation()
game_constructor = TatetiConstructor(console_implementation)

game_constructor.configure_game()
game_constructor.start_game()